name: pocket_scat
description: goomba

version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  audioplayers: 0.18.1
  dart_random_choice: 0.1.0-nullsafety.0
  share: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.0.3
  build_runner: any
  flutter_launcher_icons: 0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/bean.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/